# How to run:
# docker-compose up -d

version: '2'
services:
  database:
    container_name: database
    image: mysql:5.6
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=arbitrium
      - MYSQL_DATABASE=arbitrium
    # volumes:
    #   - /vol/arbitrium:/var/lib/mysql
  api:
    container_name: api
    build:
      args:
        - GIT_BRANCH=038-integracao-jenkins
      context: .
      dockerfile: Dockerfile_api
    image: arbitrium_api:latest
    depends_on:
      - "database"
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
    command: ["./wait-for-it.sh", "-t", "0", "database:3306", "--", "npm", "start"]
  web:
    container_name: web
    build:
      args:
        - GIT_BRANCH=038-integracao-jenkins
      context: .
      dockerfile: Dockerfile_web
    image: arbitrium_web:latest
    depends_on:
      - "api"
    ports:
      - "3003:8080"
    environment:
      - API_SERVER=api
      - API_PORT=3004
