FROM ubuntu:16.04
RUN apt-get update && apt-get upgrade -y

# Install node and git
RUN apt-get install -y curl git-core build-essential wget
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash
RUN apt-get install -y nodejs

# Get code
ARG GIT_BRANCH=dev
RUN git clone -b ${GIT_BRANCH} http://201.54.139.88/arbitrium/web.git

# Install project dependencies
RUN cd web && npm install
WORKDIR /web
CMD npm start
