module.exports =[
  {
    "id": 1,
    "activity_id": 1,
    "initial_occurences_number": 0,
    "final_occurences_number": 1,
    "family_points": 0,
    "health_points": -25,
    "money_points": 0,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 2,
    "activity_id": 1,
    "initial_occurences_number": 1,
    "final_occurences_number": 2,
    "family_points": 0,
    "health_points": 0,
    "money_points": 0,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 3,
    "activity_id": 1,
    "initial_occurences_number": 2,
    "final_occurences_number": 3,
    "family_points": 0,
    "health_points": 5,
    "money_points": -5,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 4,
    "activity_id": 1,
    "initial_occurences_number": 3,
    "final_occurences_number": 25,
    "family_points": 0,
    "health_points": 15,
    "money_points": -15,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 5,
    "activity_id": 1,
    "initial_occurences_number": 4,
    "final_occurences_number": 5,
    "family_points": 0,
    "health_points": 5,
    "money_points": -20,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 6,
    "activity_id": 15,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": 0,
    "health_points": 6,
    "money_points": 15,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 7,
    "activity_id": 16,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": -5,
    "health_points": 0,
    "money_points": -5,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 8,
    "activity_id": 2,
    "initial_occurences_number": 1,
    "final_occurences_number": 4,
    "family_points": 0,
    "health_points": 0,
    "money_points": 30,
    "work_points": 5,
    "points_type": "D"
  },
  {
    "id": 9,
    "activity_id": 2,
    "initial_occurences_number": 4,
    "final_occurences_number": 6,
    "family_points": 0,
    "health_points": 0,
    "money_points": 50,
    "work_points": 10,
    "points_type": "D"
  },
  {
    "id": 10,
    "activity_id": 2,
    "initial_occurences_number": 6,
    "final_occurences_number": 9,
    "family_points": 0,
    "health_points": 0,
    "money_points": 70,
    "work_points": 15,
    "points_type": "D"
  },
  {
    "id": 11,
    "activity_id": 2,
    "initial_occurences_number": 9,
    "final_occurences_number": 13,
    "family_points": -15,
    "health_points": -30,
    "money_points": 60,
    "work_points": 15,
    "points_type": "D"
  },
  {
    "id": 12,
    "activity_id": 2,
    "initial_occurences_number": 13,
    "final_occurences_number": 15,
    "family_points": -25,
    "health_points": -50,
    "money_points": 100,
    "work_points": 25,
    "points_type": "D"
  },
  {
    "id": 13,
    "activity_id": 2,
    "initial_occurences_number": 15,
    "final_occurences_number": 25,
    "family_points": -50,
    "health_points": -90,
    "money_points": 140,
    "work_points": 25,
    "points_type": "D"
  },
  {
    "id": 14,
    "activity_id": 3,
    "initial_occurences_number": 0,
    "final_occurences_number": 1,
    "family_points": 0,
    "health_points": -25,
    "money_points": 0,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 15,
    "activity_id": 3,
    "initial_occurences_number": 1,
    "final_occurences_number": 4,
    "family_points": 0,
    "health_points": -10,
    "money_points": 0,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 16,
    "activity_id": 3,
    "initial_occurences_number": 4,
    "final_occurences_number": 7,
    "family_points": 0,
    "health_points": 5,
    "money_points": 0,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 17,
    "activity_id": 3,
    "initial_occurences_number": 7,
    "final_occurences_number": 9,
    "family_points": 0,
    "health_points": 10,
    "money_points": 0,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 18,
    "activity_id": 3,
    "initial_occurences_number": 9,
    "final_occurences_number": 25,
    "family_points": 0,
    "health_points": 5,
    "money_points": 0,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 19,
    "activity_id": 4,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": 10,
    "health_points": 10,
    "money_points": -30,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 20,
    "activity_id": 5,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": 5,
    "health_points": 5,
    "money_points": -20,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 21,
    "activity_id": 6,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": 15,
    "health_points": 15,
    "money_points": -30,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 22,
    "activity_id": 7,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": 0,
    "health_points": 15,
    "money_points": -10,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 23,
    "activity_id": 8,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": 0,
    "health_points": 5,
    "money_points": -10,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 24,
    "activity_id": 9,
    "initial_occurences_number": 1,
    "final_occurences_number": 5,
    "family_points": -5,
    "health_points": 0,
    "money_points": -10,
    "work_points": 10,
    "points_type": "S"
  },
  {
    "id": 25,
    "activity_id": 9,
    "initial_occurences_number": 5,
    "final_occurences_number": 9,
    "family_points": -10,
    "health_points": -5,
    "money_points": -10,
    "work_points": 15,
    "points_type": "S"
  },
  {
    "id": 26,
    "activity_id": 9,
    "initial_occurences_number": 9,
    "final_occurences_number": 120,
    "family_points": -15,
    "health_points": -10,
    "money_points": -10,
    "work_points": 20,
    "points_type": "S"
  },
  {
    "id": 27,
    "activity_id": 10,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": 5,
    "health_points": 0,
    "money_points": -5,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 28,
    "activity_id": 11,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": 0,
    "health_points": 0,
    "money_points": -10,
    "work_points": 5,
    "points_type": "D"
  },
  {
    "id": 29,
    "activity_id": 12,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": 10,
    "health_points": 0,
    "money_points": -5,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 30,
    "activity_id": 13,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": 5,
    "health_points": 0,
    "money_points": -5,
    "work_points": 0,
    "points_type": "D"
  },
  {
    "id": 31,
    "activity_id": 14,
    "initial_occurences_number": 1,
    "final_occurences_number": 25,
    "family_points": -20,
    "health_points": 0,
    "money_points": 40,
    "work_points": 20,
    "points_type": "D"
  }
]
